[package]
name = "ket-py"
version.workspace = true
edition.workspace = true
description = "PyO3 Python bindings for Ket."
license.workspace = true
repository.workspace = true

[lib]
name = "ket"
crate-type = ["cdylib"]

[dependencies]
ket-cas.workspace = true
ket-dag.workspace = true
pyo3 = { version = "0.23", features = ["auto-initialize"] }
serde_json.workspace = true
